### ISSUE TITLE
Feature Request # 2

### ISSUE THREAD

**Issue by SMAPPER** [MarkBaggett/MarkBaggett#3]
I am currently working towards having freq.py integrate with Logstash.  I am calling freq.py and passing things such as domain names, file names, SSL subject names, etc as log data comes in and saving the results as an extra field.  In preliminary tests this has been absolutely amazing and I believe will significantly help my analysts find outliers or have better insight on abnormal events.

However, when I test in production everything tends to score the exact same or has a value of zero.  Looking into this it looks like it is related to freq.py writing out files based on the frequency table.  Do you know if there is something simple that could be done to allow for this script to be ran hundreds of times a second?  I'm assuming it's writing out and reading a file per call which is causing this behavior.

Once I have this working I'm going to post a blog on using your freq.py with log solutions as I think this is a huge advantage companies are not considering.

**Comment by MarkBaggett** [comment]
Interesting.   I am happy to help and get this fixed but I'm not sure I understand the problem at the moment.  Is the problem being caused by the frequency table becoming corrupt?   Are you learning from every log?  It is a volume issue that would just require that I add threading support?    Is there a way you can show me the result?   Email me directly and we can see if we can webex or something to look at what's going on together.   

Mark

**Comment by SMAPPER** [comment]
Sorry for the late response.  I just flew back in from Japan.  I do not
have your email but if you want you can reach me directly at
jhenderson@tekrefresh.com.  I would really appreciate working with you on
this as I think it's use case is fairly large and extremely useful.

I am available most of this week during the day and also anytime in the
evening after 8:30 PM CST.  Thanks for your help on this!


Sincerely,

Justin Henderson
(217) 821-9479
Systems and Security Architect
GSE # 108
http://www.linkedin.com/in/justinhenderson2014/

**Comment by MarkBaggett** [comment]
Addressed with freq_server.py
